import {HomeServices,Testimonials,CTASection,QuoteSection,CompanyDetails} from '../components/Sections';
import {serviceDetails} from '../lib/service-details';
import {services} from '../lib/service-catalog';
import {features} from '../lib/features';
import {useState,useEffect} from 'react';
import {AnimatePresence,motion} from 'motion/react';
import {ArrowLeft,ArrowUpRight} from 'lucide-react';
import Hero from '../components/motion/Hero';
import {BookingSection,Process,ServiceApproach,BrandStrip,Intro,ServicesSection,WorkRibbon,AboutTeaser,Pricing,FAQ,Recognition,RecentWork} from '../components/Sections';
import {Button,Reveal,SectionHeading,ProjectCard,ProjectImage} from '../components/ui/Primitives';
import {projects} from '../lib/data';
import {Link} from '../lib/router';
import BookingForm from '../components/BookingForm';
import {handleTabKeys} from '../lib/utils';
export function Home({onSelect}){return <><div className="opening"><Hero/><BrandStrip/></div><AboutTeaser/><Intro/><HomeServices/><WorkRibbon/>{features.pricing&&<Pricing onSelect={onSelect}/>}<Recognition/><RecentWork/><Testimonials/><FAQ/><CTASection/><BookingSection/></>}
export function About(){return <><Hero page="about" title="About" eyebrow="Developer & digital partner" description="The person behind the work."/><section className="section who-i-am"><SectionHeading label="Who I Am" title={<>Development with<br/>Purpose and<br/>Personality</>} description="Building meaningful digital products through thoughtful engineering and collaboration."><div className="body-copy"><p>I’m an independent developer combining web, app, and automation expertise with a strong eye for design. My approach connects technical choices to what your users and business actually need.</p><p>I work across React, Python, AI integrations, data, and content platforms. Clear communication, accessible interfaces, and maintainable code shape every project.</p><p>Whether you’re building something new or finding a fresh direction, we’ll turn your ambitions into a clear roadmap and a useful digital product.</p></div></SectionHeading></section><QuoteSection/><AboutTeaser/><Process compact/><Recognition/><WorkRibbon/><ServiceApproach/><CTASection/></>}
export function Services({onSelect}){return <><Hero page="services" title="Services" eyebrow="Built with purpose" description="Your next chapter starts with a clear idea."/><ServicesSection full/><Process/>{features.pricing&&<Pricing onSelect={onSelect}/>}<RecentWork/><Testimonials/><FAQ/><CTASection/><BookingSection/></>}
export function Projects(){const [filter,setFilter]=useState('All');const filtered=projects.filter(p=>filter==='All'||p.category===filter);return <><Hero page="projects" title="Projects" eyebrow="Selected Work" description="Real ideas, thoughtfully brought to life."/><section className="section"><SectionHeading label="Selected Work" title={<>Bringing Ideas<br/>to Life Through<br/>Code</>} description="A collection of development studies across websites, applications, data, and digital experiences."><p className="muted mt-6">Illustrative development studies. Replace these previews with your own project screenshots before publishing.</p></SectionHeading><div role="tablist" onKeyDown={handleTabKeys} aria-label="Project categories" className="filter-tabs">{['All',...new Set(projects.map(p=>p.category))].map(f=><button role="tab" tabIndex={filter===f?0:-1} aria-selected={filter===f} aria-controls="project-results" onClick={()=>setFilter(f)} key={f}>{f}</button>)}</div><div className="projects-grid" id="project-results"><AnimatePresence mode="popLayout">{filtered.map(p=><motion.div layout key={p.id} initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} exit={{opacity:0,scale:.95}} transition={{duration:.3}}><ProjectCard project={p}/><p className="muted project-description">{p.subtitle}</p></motion.div>)}</AnimatePresence></div></section><RecentWork/></>}
export function ProjectDetail({id}){const p=projects.find(p=>p.id===id);if(!p)return <NotFound/>;return <><Hero page="project-detail" title={p.name} eyebrow={p.category} description={p.subtitle}/><section className="section detail-top"><Link to="/projects" className="text-link"><ArrowLeft size={17}/> Back to projects</Link><div className="detail-title"><div><p className="eyebrow">{p.category} / Concept project</p><h1>{p.name}</h1></div><p>{p.subtitle}</p></div><div className="case-image"><ProjectImage src={p.image} alt={p.name+' project'} loading="eager"/></div><div className="case-meta"><span>{p.year}</span><span>Independent concept</span><span>{p.category}</span></div></section><section className="section case-body"><Reveal><p className="eyebrow">The Project</p><h2>A clear idea.<br/>A distinct identity.</h2></Reveal><Reveal><h3>{p.description}</h3><div className="body-copy"><h4>The challenge</h4><p>{p.challenge}</p><h4>The direction</h4><p>{p.solution}</p><h4>The deliverables</h4><ul className="tag-list">{p.deliverables.map(d=><li key={d}>{d}</li>)}</ul></div><Button to="/contact">Create something like this</Button></Reveal></section><section className="section"><p className="eyebrow">Keep exploring</p><h2 className="mb-10">More good things.</h2><div className="featured-grid">{projects.filter(q=>q.id!==id).map(q=><ProjectCard key={q.id} project={q}/>)}</div></section></>}
export function Contact({plan,onClear}){return <><Hero page="contact" title="Contact" eyebrow="Get in touch" description="Let’s build something great together."/><section className="section contact-section" id="book"><Reveal><p className="eyebrow">Contact me</p><h2>Let’s Create<br/>Something<br/>Meaningful</h2><h3>Whether you need a website, app, automation, or a smarter digital workflow, let’s turn your idea into a practical plan.</h3><p className="muted">Tell me what you’re thinking. Request a discovery call, and let’s explore the possibilities.</p><div className="contact-facts"><div><span>Where</span><p>Remote · Working worldwide</p></div><div><span>When</span><p>Meeting time agreed together</p></div><div><span>The first step</span><p>A friendly, no-obligation conversation</p></div></div></Reveal><div><BookingForm plan={plan} onClear={onClear}/><CompanyDetails/></div></section><FAQ/></>}
export function NotFound(){return <section className="section not-found"><p className="eyebrow">404 / A small detour</p><h1>This page is<br/>still a blank canvas.</h1><Button to="/">Back to home</Button></section>}

export function ServiceDetail({id}){const service=services.find(s=>s.id===id),detail=serviceDetails[id];if(!service||!detail)return <NotFound/>;return <><Hero page="service-detail" title={service.name} eyebrow="Development & digital services" description={detail.headline}/><section className="section"><SectionHeading label="The right solution for your goals" title={detail.headline} description={detail.overview}/><div className="service-detail-grid"><Reveal><article className="stage-card"><p className="eyebrow">Who it’s for</p><h3>A focused approach to your challenge.</h3><p className="muted">{detail.audience}</p></article></Reveal><Reveal><article className="stage-card"><p className="eyebrow">What we can deliver</p><ul className="detail-deliverables">{detail.deliverables.map((item,i)=><li key={item}><span>0{i+1}</span>{item}</li>)}</ul></article></Reveal></div></section><Process/><section className="section contact-section" id="book"><Reveal><p className="eyebrow">Let’s discuss {service.name.toLowerCase()}</p><h2>Start with<br/>a conversation.</h2><p className="muted">Share your goals and current challenges. We’ll agree the scope, deliverables, and timing before work begins.</p></Reveal><BookingForm key={service.id} defaultService={service.name}/></section><section className="section"><SectionHeading label="Keep exploring" title="Connected expertise." description="Your project may benefit from more than one discipline. Explore the services that can support your next step."/><div className="related-services">{services.filter(s=>s.id!==id).slice(0,3).map(s=><Link to={'/services/'+s.id} key={s.id}><h3>{s.name}</h3><p>{s.tag}</p><span>Learn More ↗</span></Link>)}</div></section></>}
