import {useState} from 'react';
import {CheckCircle2,ArrowRight,X} from 'lucide-react';
import {services} from '../lib/data';
import {Button} from './ui/Primitives';
export default function BookingForm({plan,onClear,defaultService}){
 const [service,setService]=useState(()=>{const name=defaultService||new URLSearchParams(location.search).get('service');return services.some(s=>s.name===name)?name:'Discovery call'});
 const [pending,setPending]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(null);
 async function submit(e){e.preventDefault();setPending(true);setError('');const values=Object.fromEntries(new FormData(e.currentTarget));try{const response=await fetch('/api/enquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...values,service,plan:plan?.id||null})});const data=await response.json();if(!response.ok)throw Error(data.error||'Could not save your enquiry. Please try again.');setSuccess(data);onClear?.()}catch(e){setError(e.message)}finally{setPending(false)}}
 if(success)return <div className="booking-card booking-success" role="status"><CheckCircle2 size={48}/><p className="eyebrow">A good beginning</p><h3>Your enquiry is saved.</h3><p className="muted">Reference: {success.id.slice(0,8).toUpperCase()}<br/>Your appointment has not been scheduled yet. A date and time can be agreed after reviewing your enquiry.</p><button className="text-link" onClick={()=>setSuccess(null)}>Make another enquiry <ArrowRight size={16}/></button></div>;
 return <form className="booking-card" onSubmit={submit}><div className="form-heading"><span className="eyebrow">Let’s arrange a conversation</span></div>{plan&&<div className="selected-plan"><p>{plan.name}</p><button type="button" className="icon-button" onClick={onClear} aria-label="Remove selected package"><X size={18}/></button></div>}<div className="form-row"><label>First name <span>*</span><input name="firstName" autoComplete="given-name" placeholder="Jane" required maxLength={60}/></label><label>Last name <span>*</span><input name="lastName" autoComplete="family-name" placeholder="Smith" required maxLength={60}/></label></div><label>Email address <span>*</span><input name="email" type="email" autoComplete="email" placeholder="jane@company.com" required maxLength={200}/></label><fieldset className="service-picker"><legend>What can I help with?</legend><div className="service-options">{['Discovery call',...services.map(s=>s.name)].map(name=><label key={name} className={'service-option '+(service===name?'is-selected':'')}><input type="radio" name="service" value={name} checked={service===name} onChange={()=>setService(name)}/><span>{name}</span></label>)}</div></fieldset><label>A little about your project<textarea name="message" rows="4" placeholder="Your idea, goals, and what you need help with…" maxLength={3000}/></label><label className="consent"><input type="checkbox" name="consent" required/>I agree to share these details for this project enquiry.</label>{error&&<p className="form-error" role="alert">{error}</p>}<div className="booking-submit"><Button type="submit" disabled={pending}>{pending?'Saving enquiry…':'Request a conversation'}</Button></div><p className="form-note">No payment required. Date and time are agreed separately.</p></form>
}
