import {motion,useReducedMotion} from 'motion/react';
import {ArrowUpRight,ArrowRight} from 'lucide-react';
import {Link} from '../../lib/router';
import {cn} from '../../lib/utils';
export function Button({children='Get in touch',to,onClick,light=false,className='',type='button',...props}){const content=<><span className="button-label">{children}</span><span className="button-icon" aria-hidden="true"><ArrowRight size={17}/><ArrowRight className="arrow-incoming" size={17}/></span></>;return to?<Link to={to} className={cn('pill',light&&'pill-light',className)} onClick={onClick} {...props}>{content}</Link>:<button type={type} onClick={onClick} className={cn('pill',light&&'pill-light',className)} {...props}>{content}</button>}
export function Reveal({children,className='',delay=0}){const reduced=useReducedMotion();return <motion.div className={className} initial={reduced?false:{opacity:0,y:55,filter:'blur(5px)'}} whileInView={{opacity:1,y:0,filter:'blur(0px)'}} viewport={{once:true,amount:.08}} transition={{duration:.9,delay,ease:[.16,1,.3,1]}}>{children}</motion.div>}
export function SectionHeading({label,title,description,children}){return <Reveal className="section-heading"><div><p className="eyebrow">{label}</p><h2>{title}</h2></div><div className="section-intro"><h3><TextReveal text={description}/></h3>{children}</div></Reveal>}
export function ProjectImage({src,alt,className='',...props}){return <img src={src} alt={alt} className={className} loading="lazy" decoding="async" onError={e=>{if(!e.currentTarget.dataset.fallback){e.currentTarget.dataset.fallback='true';e.currentTarget.src='/assets/hero.png'}}} {...props}/>}
export function ProjectCard({project,mono=false}){return <motion.article whileHover={{y:-6}} transition={{duration:.3}} className={cn('project-card',mono&&'mono-card')}><Link to={'/projects/'+project.id} className="project-image-link"><ProjectImage src={project.image} alt={project.name+' — '+project.category}/><span className="view-project">Explore project <ArrowUpRight size={20}/></span></Link><div className="project-caption"><div><h3><Link to={'/projects/'+project.id}>{project.name}</Link></h3><p>{project.category}</p></div><span>{project.year}</span></div></motion.article>}

export function TextReveal({text}){const reduced=useReducedMotion();return <span aria-label={text}>{text.split(' ').map((word,i)=><span className="reveal-word-mask" aria-hidden="true" key={i}><motion.span initial={reduced?false:{y:'110%',opacity:0}} whileInView={{y:0,opacity:1}} viewport={{once:true}} transition={{duration:.6,delay:i*.025,ease:[.16,1,.3,1]}}>{word} </motion.span></span>)}</span>}
